### ISSUE TITLE
[BUG] Error occured while disabling MyticDrops

### ISSUE THREAD

**Issue by SirKillian** [MythicDrops/MythicDrops#674]
## Description
When the server shuts down, there is an error.

## Expected Behavior
No errors during shutdown

## Actual Behavior
error log: https://paste.helpch.at/ewokafoceg.log

## Steps to Reproduce
1. shut down the server

## Your Environment
* Version used (`/version MythicDrops`): 8.3.5
* Environment name and version (`/version`): Paper 1.19 build 43

**Comment by ToppleTheNun** [comment]
This has been fixed in 8.4.0, which will be available on GitHub Releases shortly.
