### ISSUE TITLE
[BUG] socketTypes.yml - %tiercolor%(Socket) problem (version 8.4.1)

### ISSUE THREAD

**Issue by zorkenlide** [MythicDrops/MythicDrops#700]
With these settings, the %tiercolor% is not recognized as a valid color and even with ignore-colors: true, sockets cant be inserted into the item:

    socket-style: '%tiercolor%(Socket)'
    ignore-colors: true

(We used to have the sockets in the same color as item name, before the update, so I tried to configure it the same way after the update. When I change it to '&8(Socket)', it does work. However, my players cant insert the sockets into the items generated before this update.)

Version 8.4.1, Paper 232 1.19.2

**Comment by ToppleTheNun** [comment]
Do the items in question have `%tiercolor%(Socket)` in the lore of the item?
