### ISSUE TITLE
[BUG] Anvil repairing does not work for vanilla (non-mythic) items [MD 8.4.2]

### ISSUE THREAD

**Issue by zorkenlide** [MythicDrops/MythicDrops#704]
Anvil for MD items work as intended, but when I, for example, put damaged vanilla bow into it and I want to repair it with another bow, the anvil output shows repaired bow for 0.1 sec and then disappears.

## Steps to Reproduce
1. create a clean paper server (Paper version git-Paper-307 (MC: 1.19.2))
2. put only some basic plugins in the plugins folder (I am using CMI, ItemsAdder, MythicDrops, LuckPerms)
3. try to repair some vanilla (non-mythic item) in the anvil - it wont work
4. When you remove MythicDrops.jar from the plugins folder and restart the server, anvil works.

## Your Environment
MD 8.4.2
Paper version git-Paper-307 (MC: 1.19.2)
[config.txt](https://github.com/MythicDrops/MythicDrops/files/10801388/config.txt)

**Comment by SirKillian** [comment]
Having the same issue on Mythicdrops 8.4.4 on 1.19.3 paper build 431
