### ISSUE TITLE
Incorrect Enchantments

### ISSUE THREAD

**Issue by TangledWiresYT** [MythicDrops/MythicDrops#730]
Is it possible to disable having enchantments like smite on a chestplate or protection on an axe?

![image](https://github.com/MythicDrops/MythicDrops/assets/68852080/be6d3f13-9b6c-4f20-91a1-f324773bfc74)

**Comment by ToppleTheNun** [comment]
Enable `safe-base-enchantments` and `safe-bonus-enchantments`.

**Comment by TangledWiresYT** [comment]
> Enable `safe-base-enchantments` and `safe-bonus-enchantments`.

Thank you
